# Generated by Django 3.0.5 on 2022-08-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamManagement',
            new_name='Document',
        ),
    ]
