# Generated by Django 3.2.9 on 2022-07-26 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_filemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.exammanagement', verbose_name='Upload'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='doc',
            field=models.FileField(default=None, upload_to='static/'),
        ),
    ]
