# Generated by Django 3.2.9 on 2022-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220726_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammanagement',
            name='status',
            field=models.BooleanField(verbose_name='Trạng thái xuất bản'),
        ),
    ]
