# Generated by Django 3.0.5 on 2022-08-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220809_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_corect',
            field=models.BooleanField(default=False, verbose_name='Đáp án đúng'),
        ),
    ]
