# Generated by Django 3.2.9 on 2022-08-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_exammanagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammanagement',
            name='doc',
            field=models.FileField(default=None, upload_to='static/file/'),
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
