# Generated by Django 3.0.5 on 2022-08-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220810_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_corect',
            new_name='is_correct',
        ),
    ]
