# Generated by Django 3.2.9 on 2022-08-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220801_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammanagement',
            name='doc',
            field=models.FileField(blank=True, upload_to='static/file/'),
        ),
    ]
