# Generated by Django 3.2.9 on 2022-08-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_exammanagement_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300, verbose_name='Nội dung câu hỏi')),
                ('ordering', models.CharField(max_length=300, verbose_name='Số thứ tự câu hỏi')),
                ('exam_Management', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.exammanagement')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300, verbose_name='Câu trả lời')),
                ('ordering', models.CharField(max_length=300, verbose_name='Số thứ tự câu trả lời')),
                ('is_corect', models.BooleanField(verbose_name='Đáp án đúng')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.question')),
            ],
        ),
    ]
